### ISSUE TITLE
Scopes with arguments

### ISSUE THREAD

**Issue by russ** [anykeyh/clear#10]
It would be really nice to support scopes that have arguments on them.

For a simple "contrived" example, something like this.

```
class Post
  include Clear::Model

  scope("for_categories", categories : Array(Int32)) do
    where("category_id IN ?", categories.join(",")})
  end
end
```

**Comment by anykeyh** [comment]
The usage is:

```crystal
scope("for_categories") do |categories|
    where category_id: categories
end
```

Note than with block, we cannot force a specific type for the arguments. So compile time checking of argument type will be delegated on calling of the scope.
