### ISSUE TITLE
Defining Model#from_json

### ISSUE THREAD

**Issue by zbaylin** [anykeyh/clear#107]
As far as I can tell right now, `Clear::Model` only provides a `#to_json` method, but nothing to convert back out of JSON. I can't seem to get `JSON.mapping` to work inside my model, because every time I come back from JSON, I get
```
Exception: You're trying to access to the column `xxx` but it is not initialized.
...
  - If your model comes from JSON, please ensure the JSON source defines the                        
    column. Usage of `strict` mode will trigger exception on JSON loading.    
```
This means that right now there doesn't seem to be a way to convert __from__ JSON, which breaks support for things like session storage in `kemal-session`, etc.

**Comment by anykeyh** [comment]
Yes currently the converter convert only from and to PostgreSQL. Adding methods to convert from and to json would be a plus.
