### ISSUE TITLE
model callback not auto transaction

### ISSUE THREAD

**Issue by pynixwang** [anykeyh/clear#109]
I must wrap it myself.

**Comment by anykeyh** [comment]
Hello, I didn't get your message...

**Comment by pynixwang** [comment]
@anykeyh 
no 

for example:
```
after :create, :decrement_balance
```

`decrement_balance` should be wrap into `create` transaction like this.

```
BEGIN
INSERT INTO ORDER
UPDATE users SET
COMMIT
```
