### ISSUE TITLE
Great. Unfortunately, lack of documentation is difficult for beginners.

### ISSUE THREAD

**Issue by isled** [anykeyh/clear#11]
If you can improve the document. This is a very good program. It's the best in crystal.

**Comment by anykeyh** [comment]
Indeed, for now I guess the best way is to ~~read~~ decipher the specs and the Readme.

I'll look forward to create a real guide.

**Comment by anykeyh** [comment]
Meanwhile, you can check https://github.com/anykeyh/clear/blob/master/sample/wiki/getting_started.cr
which is stand-alone example.

It doesn't show all the features of the ORM but the most common. If you have any issues with unexplained features, feel free to comment here. 😄

**Comment by g-maple** [comment]
It took half a day to read the whole source code, and it was easy to understand. However, in specific applications, the lack of documents may take more time. But it doesn't rule out this is a great project. Thank you for your answer.

**Comment by anykeyh** [comment]
Hello,

I've been working on the documentations, you can find some guides in [the wiki](https://github.com/anykeyh/clear/wiki)

I think this should cover most of the features !

I'll keep the issue open and continue to improve the guide.
