### ISSUE TITLE
clear 1.0

### ISSUE THREAD

**Issue by wontruefree** [anykeyh/clear#114]
I am curious is there a roadmap to clear 1.0?

**Comment by anykeyh** [comment]
Here but not updated for a while: https://github.com/anykeyh/clear/projects/1

But basically for 1.0, I would say:

- Proven stability
- Better spec and coverage
- Better runtime reflection
- Better relations
    - has_many through issues fix
    - polymorphic relations
- Better caching management (currently won't cache certains relations)
- More PG structures and operators managed (time, interval, citext etc...)

**Comment by wontruefree** [comment]
Thanks for the response I cant wait for 1.0.
