### ISSUE TITLE
Doing raw select queries

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#117]
Sometimes the SQL might get a little too complicated to build out a model, and you may want to run a raw SQL query instead. Clear currently has an [execute](https://github.com/anykeyh/clear/blob/master/src/clear/sql/sql.cr#L173) method to run raw queries, but this doesn't seem to return anything useful (that I can tell).

```crystal
require "clear"
Clear::SQL.init("default", "postgres://localhost:5432/sample")
result = Clear::SQL.execute("SELECT 1 + 1")
#=> DB::ExecResult(@rows_affected=0, @last_insert_id=0)
```

With this `result` variable, I don't have a way to get the value `2` returned.

**Comment by zbaylin** [comment]
Try `Clear:: SQL.query` using the query builder DSL

**Comment by jwoertink** [comment]
Ah, ok. So using the `Clear::SQL.select` could work in the interim. It does still make things a little difficult due to having to break out each part in to separate method calls like:

```crystal
result = Clear::SQL.select("1 + 1, now()").where("1 = 1")
data = result.first
```
But that may work for what I need at the moment. Thanks @zbaylin 

However, if you start using `UNION ALL` and subselects, then breaking that out might not be possible depending on what all clear supports. So just having a method to run the raw sql and get back the result would be greatly helpful. I know crystal-db supports this with the `query` method, but I'm not sure how to get access to that within clear's current connection pool.

**Comment by anykeyh** [comment]
Hello !

You can catch the connection of the connection pool using that:

```crystal
      Clear::SQL::ConnectionPool.with_connection("default") do |cnx|
```

This return a low-level crystal-db database object so you can call `query` over it.

Otherwise, zbaylin is right about the `SelectBuilder`. And no, `UNION` are not yet supported by the builder :smile: (but would be very easy to support with a little bit of time).

**Comment by jwoertink** [comment]
Ok sweet. Yeah, I was able to get my query in using `Clear::SQL.select...`. I'll go ahead and close this out for now. Thanks!
