### ISSUE TITLE
UNIX sockets

### ISSUE THREAD

**Issue by Lukc** [anykeyh/clear#120]
Hello,

The documentation does not mention how to connect to postgres through UNIX sockets. Is that currently possible?

Cheers,

**Comment by anykeyh** [comment]
Hello,

I have no idea if it's possible. I think this question should be asked at the [pg shard team](https://github.com/will/crystal-pg). 
Clear just delegate the connection initialization method to Crystal's DB API

**Comment by remydev** [comment]
https://github.com/will/crystal-pg/issues/168 #

**Comment by remydev** [comment]
https://github.com/will/crystal-pg/issues/168
