### ISSUE TITLE
String substitution in SELECT

### ISSUE THREAD

**Issue by zbaylin** [anykeyh/clear#128]
Sometimes you might want to do string substitution in a SELECT, like when using a CASE statement. Currently this doesn't seem possible, or, if it is, I can't seem to find out how to do it. Crecto used to support this with the traditionally used `$1` or `?` when doing a raw SELECT.

**Comment by anykeyh** [comment]
This is doable since `v0.8`, both with `?` + `Tuple` and `:xxx` + `NamedTuple`

```crystal
Mode.query.select( 
  Clear::SQL.raw("CASE WHEN x=:x THEN 1 ELSE 0 END as check", x: "blabla") 
)
```
