### ISSUE TITLE
Calling count on paginated query

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#13]
When you do a count, it returns 1 row. Doing a limit is pointless since you only get 1. Doing an offset will end up returning nothing.

```sql
db=# SELECT COUNT(*) FROM users LIMIT 100 OFFSET 0;
  count
---------
 1901902
(1 row)

db=# SELECT COUNT(*) FROM users LIMIT 100 OFFSET 25;
 count
-------
(0 rows)
```

If you have a query setup, and happen to call `count` on it, it will blow up with an exception.
```crystal
User.query.limit(100).offset(0).count #=> 1901902_i64
User.query.limit(100).offset(25).count #=> 
# Error catched, last request was:
# SELECT COUNT(*) FROM users LIMIT 100 OFFSET 25
# no results (Exception)
```

Maybe in this case if it knows there's a limit and offset, it does something like `query.to_a.size`, just return 0, or maybe a nice exception like `InvalidCountWithOffsetException` (or a better name).

**Comment by anykeyh** [comment]
Indeed, I'm figuring out what would be the best behavior (e.g. check what other ORM do in this case 😄) and I will fix the shards

**Comment by anykeyh** [comment]
ActiveRecord transform to subquery when there's a count with offset and limit:

```sql
SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "project_tasks" LIMIT $1 OFFSET $2) subquery_for_count
```

It seems to be a good way to tackle the problem; plus it makes sense to have information about count in case of pagination, for the last page for example.

It should be able to do that in Clear too. I'll try to fix during the day.

**Comment by jwoertink** [comment]
Awesome. Thanks!
