### ISSUE TITLE
Mispelled release

### ISSUE THREAD

**Issue by Acciaiodigitale** [anykeyh/clear#135]
Probably this relase Is intended to be 0.7.1 and not 7.1

**Comment by anykeyh** [comment]
Yeah, than you to point this out. 

I will basically throw away this release with the release of 0.8

**Comment by eliasjpr** [comment]
Anytime when this update will happen. I am one of the main AmberFramework contributors and I am using Clear for a production project.

**Comment by anykeyh** [comment]
Hello!

All right I'm going to ensure that is done before the end of the week. 😉

**Comment by anykeyh** [comment]
Hello,

I've fixed the release now 

You might want to try because it's the first time I edit a release like this :smile: 
I'm feeling shameful to make you wait for so long as it was just as easy as 3 clicks.

Please reopen if you have any trouble !
