### ISSUE TITLE
Clear doesn't throw any error if it fails to connect to the database

### ISSUE THREAD

**Issue by RemiKalbe** [anykeyh/clear#137]
Clear doesn't throw any error if it fails to connect to the database if the IP address of the client isn't whitelisted by the database.

I forgot I was on my VPN and I didn't understand why when I run `crystal run` nothing was happening, my terminal was waiting endlessly, and then I remembered I was on my VPN.

Clear should throw an error in this case.

I spent too much time trying to figure out why my code wasn't working anymore.

**Comment by anykeyh** [comment]
In my case, in case of wrong URL, the connection timeout after 21 seconds:

```
Finished in 21.04 seconds
Unhandled exception:  (DB::ConnectionRefused)
...
Caused by: Cannot establish connection (PQ::ConnectionError)
...
Caused by: Error connecting to '*****:5432': Connection refused (Errno)
```

Clear use Crystal's db connection so I don't know how I can really timeout the connection without makling a mess.
