### ISSUE TITLE
float types?

### ISSUE THREAD

**Issue by sam0x17** [anykeyh/clear#139]
I have a table with some float values on some of the fields. It doesn't look like clear supports float columns?

**Comment by sam0x17** [comment]
never mind, I tried it out and it is supported. Maybe something to add to to the docs!

**Comment by anykeyh** [comment]
Yeah it supports the basic primitives type. However you point out a great question, about how it handles Decimal (aka fixed floating point) type (spoiler: I never used so I might investigate it soon).
