### ISSUE TITLE
Question on typecasting

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#14]
Currently I'm having to do something like this:

```crystal
User.query.where { whatever == true }.each do |query|
  user = query.as(User)
  # do stuff with user
end
```

Is there a way currently to just push that cast to each object in the returned collection? or is this way the better option? I can't imagine that the collection would return a random nil in the set like `[<#User>, nil, <#User>]`, but if I don't cast to the class, then I get undefined method errors for compile time `User | Nil`

**Comment by anykeyh** [comment]
Hello,

It seems weird, and you should not have to typecast the object. 
Actually in the specs I never cast any objects in the collections.

Is it possible to give me a small fully repeatable example of this behavior and/or to copy me the declaration of your class User?

For the `nil`, it's 100% safe anyway.

**Comment by jwoertink** [comment]
hmm.. I wonder if I'm doing something weird then. I'm gonna mess around with this a little bit and see what's up. I'll try to recreate a sample if I can.

**Comment by jwoertink** [comment]
Ok, looks like updating fixed whatever was wrong. Using latest version and things seem to be working! Guess I should have tried that first lol. Thanks
