### ISSUE TITLE
where to place seed files?

### ISSUE THREAD

**Issue by sam0x17** [anykeyh/clear#140]
I have a seed file with `Clear.seed` defined. Where do I place it so when I run `clear-cli migrate seed` it will seed the database?

**Comment by anykeyh** [comment]
Hello,

There's currently no `clear-cli` binary.

How works the CLI is like this:

```crystal
# In your entry point
Clear.with_cli do
  App.run # or Server.start or other, for example when I use it, it is Kemal.run
end
```

Then just call the cli using `-- clear`:

```text
# Seed 
$ crystal run src/entrypoint/server.cr -- clear seed
# Migrate
$ crystal run src/entrypoint/server.cr -- clear migrate
# All command and subcommand have help for advanced usage:
$ crystal run src/entrypoint/server.cr -- clear migrate --help
```

**Comment by sam0x17** [comment]
thanks!

**Comment by sam0x17** [comment]
also by the way is there any way with the cli passthrough to drop and create the database? If not, I can make a `Cakefile` for that.

**Comment by anykeyh** [comment]
Not yet, better to get a Cakefile indeed :-)
