### ISSUE TITLE
Raising exception on missing field

### ISSUE THREAD

**Issue by waghanza** [anykeyh/clear#145]
Hi @anykeyh,

Thanks for your great work. This library is simple and elegant to use :+1: 

However, I've defined a model in https://github.com/openbadminton/core-api/blob/players/src/object/player.cr

As far as I understand, `presence` validator is on **true**, by default

However, when I create an object according to above model (from json)
https://github.com/openbadminton/core-api/blob/players/src/api.cr#L18

any exception is raised ?

How can I raise any exception for a missing field ?

Regards,

**Comment by anykeyh** [comment]
Exception are raised during validation phase. 

You can check whether a model is valid by calling:

```crystal
my_model.valid? # => will return true or false
my_model.valid! # => will raise InvalidModelError if the model is invalid, or return the model if it's valid
```

**Comment by waghanza** [comment]
and how can I catch the validation issue ?

**Comment by anykeyh** [comment]
You have a field called `errors` that lists all the failed validation after you tried to validate (via `valid?` `valid!`, `save` or `save!`:

```crystal
unless model.valid?
  model.errors.each do |error|
    puts "The column `#{error.column}` is invalid because `#{error.reason}`"
  end
end
```

**Comment by waghanza** [comment]
I've build a `Hash`
~~~json
player.as(Player).errors.each do |error|
          errors[error.column.as(String)] = error.reason.as(String)
        end
~~~
 to send a `json` **errors**, but I have 
~~json
{"error":{"id":"must be present","license":"must be present"}}
~~~
should not `id` be escaped in `Clear::Model::HasValidation` ? since this field, as a **primary** should be created by the database, and not the user

**Comment by anykeyh** [comment]
You need to declare your primary key by calling `primary_key` in your model:

```crystal
class Player 
  include Clear::Model

  primary_key
end
```

You can find more informations [here](https://clear.gitbook.io/project/model/column-types/primary-keys)
