### ISSUE TITLE
.to_json fails on Array data types

### ISSUE THREAD

**Issue by zbaylin** [anykeyh/clear#155]
If I have a model with:
```crystal
class Group
    include Clear::Model
    self.table = "groups"

    ...

    column locations : Array(String)

    ...

end 
```

If I call `group.to_json` on an instance of that class, I get:

```
Exception: Expected string for object name (JSON::Error)
```

**Comment by zbaylin** [comment]
I think I found out the issue. It has to do with the way `to_json` is called. From what I can tell, `to_json` is equivalent to `to_h.to_json`. However, since I am using a custom array converter, the type of locations is `Clear::Expression::UnsafeSql`, when it should be the actual type converted.

Is there a way to fix this? @anykeyh this is related in part to #150, but I think it also applies to String arrays (which are built in).

**Comment by zbaylin** [comment]
Update: I can confirm this also happens on integer arrays

**Comment by anykeyh** [comment]
I've made a change to the `to_json` method; before it was using the database converted value, now it use directly the crystal object.
