### ISSUE TITLE
Deprecation warning in Crystal 0.34.0

### ISSUE THREAD

**Issue by mamantoha** [anykeyh/clear#173]
Stdlib `Logger` is [deprecated](https://github.com/crystal-lang/crystal/pull/8847), and should be replaced with the new `Log` module.

**Comment by anykeyh** [comment]
Yep it's already fixed in the branch v0.9

I won't deploy the branch before end of April however.

**Comment by mamantoha** [comment]
Cool. Good to know. Thanks!

**Comment by sam0x17** [comment]
@anykeyh would love to see some movement on this <3

**Comment by anykeyh** [comment]
Shards has been updated to 0.35.2
