### ISSUE TITLE
Model create not respecting schema

### ISSUE THREAD

**Issue by u89012** [anykeyh/clear#178]
The following queries fine but doesn't create, could be a bug I think. Can someone please confirm?

```
module Products
  class Listing
    include Clear::Model
    self.schema = "products"
    self.table = "listings"

    column id : Int64, primary: true, presence: false
    column title : String?
  end
end

# respects schema, works fine
Products::Listing.query.each { |a| puts a.title }

# FAILS tries insert into "listings" without the schema prefix
a = Products::Listing.create(title: "iPhone")
```

**Comment by anykeyh** [comment]
Yes, it's a bug. 
You might trick the system by naming your table `products.listings`.

**Comment by u89012** [comment]
Thank you for confirming. That's too bad I can't do that as I'm working with a legacy database. I thought I saw references to ```self.schema``` in the code when I looked up on how to include the schema information for the model. Any chance this will be fixed soon?

**Comment by anykeyh** [comment]
You can use the v0.9 branch, this has been fixed now.
