### ISSUE TITLE
Ambiguous columns with joins

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#19]
When you have joins, the select is ambiguous. If the results returns the same column name across multiple tables, Clear will map to the last returned in the set which will most likely be wrong.

```crystal
Actor.query.join("performances") { performances.actor_id == actors.id }.join("plays") { plays.id == performances.play_id }.join("releases") { releases.releaseable_id == plays.id }.where { releases.city_id == 88 }.to_sql
```

```sql
database=> SELECT * FROM actors INNER JOIN performances ON ((performances.actor_id = actors.id)) INNER JOIN plays ON ((plays.id = performances.play_id)) INNER JOIN releases ON ((releases.releaseable_id = plays.id)) WHERE (releases.city_id = 88)
-[ RECORD 1 ]--------------
id                         | 29396
name                       | Alisa Coleman
cached_slug                | alissa-coleman
id                         | 56186
actor_id                   | 29396
name                       | Dance Show
cached_slug                | dance-show
id                         | 53926
releaseable_id             | 53926
city_id                    | 88
 ```

In this example, iterating over `actors.each do |actor|`, the first `actor.id` and `actor.cached_slug`, and `actor.name` will all be wrong.

**Comment by jwoertink** [comment]
A temp fix for this would be to always use the `select` method for anyone that runs in to this.

`Actor.query.select("actors.*").join("performances")...` This will reduce what comes back from postgres to only be the Actor stuff.

**Comment by jwoertink** [comment]
Ok, so this temp fix doesn't really solve all the issues. It's also an issue when using the `with_whatever` methods. It generates SQL like `SELECT * FROM store_ratings WHERE store_id IN (SELECT id FROM stores)`. I think [this line](https://github.com/anykeyh/clear/blob/master/src/clear/model/modules/has_relations.cr#L55) and a few others in this file are what need to be patched to do `select("primary_table.#{%primary_key}")`. I poked around a bit, but had trouble figuring out what was the primary table variable to fix that. But if it generated `IN (SELECT stores.id FROM stores)`, that would fix it.

**Comment by anykeyh** [comment]
Hello,

Nice catch, I'll figure out how to fix.

**Comment by anykeyh** [comment]
It's fixed, however in case of use specific select clause, ambiguity must be deal with manually 😉
