### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by batarian71** [anykeyh/clear#20]
Hi. I am a graphic designer. I would like to volunteer to design a logo for this repository that you can use in the readme file. What do you say?

**Comment by anykeyh** [comment]
Hello,

That's a great idea ! 🎉.

I think something related to a crystal (the language), or to water (clear) would do the job. But I'm open to any proposals. 

Just please keep it simple :wink:

**Comment by batarian71** [comment]
Sorry. I am late. I wanted to design a solid and beautiful logo. I hope you liked it. What do you think? Which one?

![clear](https://user-images.githubusercontent.com/36008612/42271278-9bddf406-7f8b-11e8-8b73-a28cb2914647.jpg)

**Comment by anykeyh** [comment]
I personnaly like the bottom right one.

@jwoertink @007lva @russ Since as contributor, what do you think? 😄

**Comment by batarian71** [comment]
Is there a place you want to fix?

**Comment by anykeyh** [comment]
So I like the bottom right one, maybe you can make the main droplet a bit more "round" and slightly less big (it turns out it looks a bit too much like a penis for now hehe).

**Comment by batarian71** [comment]
Of course

**Comment by jwoertink** [comment]
I really like either of the bottom two. I would lean more towards the left one personally, but the right one looks nice too.

**Comment by batarian71** [comment]
I made it into a flat.What do you think?
![clear](https://user-images.githubusercontent.com/36008612/42344067-d42f56c4-80a3-11e8-92d0-f3fd65baf876.jpg)

**Comment by russ** [comment]
I like that version better than the other ones. I do think the font needs to change though.

My other concern is how does this relate to postgres or clear being an optimized client for it. I took a look at some of your other logos and they have a pretty good relation to the project purpose or name.

**Comment by anykeyh** [comment]
I definitely like the last logo, but the comment of @russ make sense too 😛.

Up to you @batarian71 if you wanna go the long way, I do like this logo too 😄

Once done, would be great to have:
- The SVG version of the logo
- A PR with the logo so your name will be automatically added in contributors list :+1:
- A licence for the logo

**Comment by batarian71** [comment]
I've provided the formats you want.
