### ISSUE TITLE
Calling count on an ordered query throws error

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#21]
When calling count like in pagination, if the query is ordered, then postgres will throw an error.

```ruby
User.query.where { whatever }.order_by(stuff).paginate(...)
```

```
column "whatever" must appear in the GROUP BY clause or be used in an aggregate function
```

This should be an easy fix by calling `clear_order_bys` before calling a count, but I'm not sure what other implications that might have.

**Comment by anykeyh** [comment]
That's a problem where we should decide what to do:

- We can completely wipe out GROUP BY or ORDER BY or both in case of aggregate function

But we would face a problem:

If I want to get the max of the first user:

```crystal
User.join("posts"){ users.id == posts.user_id }.group_by("users.id").order_by("users.id").max("posts.id")
```

This works, but if we wipe out everything, it will not anymore.

The best would be to wipe-out in smart way if possible.

I'll think about it few days before implementing a solution

**Comment by anykeyh** [comment]
Actually, `order_by` can be removed, while `group_by` must remains. The simple fix was to subquery the count if `group_by` is found, and to clear the `order_by`
