### ISSUE TITLE
Support Crystal 1.0.0-dev branch via any

### ISSUE THREAD

**Issue by duraki** [anykeyh/clear#212]
Hi! Can we port pg to (*) on one of the tag?

https://github.com/anykeyh/clear/blob/157cf630112bf1690816cc5cfa8051d457f546da/shard.yml#L28 might fail:

```
Fetching https://github.com/anykeyh/clear.git
Unable to satisfy the following requirements:

- `pg (*)` required by `shard.yml`
- `pg (branch master)` required by `clear 0.9+git.commit.157cf630112bf1690816cc5cfa8051d457f546da`
Failed to resolve dependencies
``` 

but pg (*) would satisfy:

```
  pg:
    github: will/crystal-pg
```

Everyone should follow-up. Thanks.

**Comment by anykeyh** [comment]
I will provide support this weekend :+1:
