### ISSUE TITLE
JSON::Serializable support

### ISSUE THREAD

**Issue by Blacksmoke16** [anykeyh/clear#26]
First off, great work with this!  Am really liking what im seeing so far :)

One feature i would like to request would be support for Crystal's `JSON::Serializable`.

The ability to do `Model.from_json(json_str)` would be quite valuable to me.  As well as being able to call `.to_json` on an object and have it serialized to JSON.

**Comment by anykeyh** [comment]
Hello,

Glad you like it ! There's still many small pesky bugs however, just push issues, I'm very reactive 👍

That's a great idea indeed, and if JSON support is possible, I guess support of `JSON::Serializable` would be impossible as of now. 

`JSON::Serializable` uses the annotations over instance variables, and in Clear the fields of your models are wrapped into a class `Column`, to allow to check if they was initially returned by the select clause or if they have changed over persisted model.

The seconds problem is the Converters which are built for SQL conversion, not JSON.

I'll figure out how I can build a poor's man solution 👍.

**Comment by Blacksmoke16** [comment]
Gotcha, thanks!
