### ISSUE TITLE
Documentation on clear when retrieving.

### ISSUE THREAD

**Issue by shayneoneill** [anykeyh/clear#28]
So I'm trying to retrieve a record from the database, and having some issues here. I'm using the following code;-

model
```
require "clear"

class User
  include Clear::Model
  with_serial_pkey
  column username : String
  column password : String
  column auth_key : String
  column auth_user : String
  column session_id : String
  column expires : Time
  column updated_on : Time
  column created_on : Time 
  self.table = "user"
end
```
The updated/created lines are there rather than the 'timestamps' clause as the DB is created by a different app.

Test code;-
```
require "clear"
require "./lib/models"
Clear::SQL.init("postgres://SNIPPED@localhost:5432/SNIPPED")
Clear.logger.level = ::Logger::DEBUG

User.query.each do |user|
  puts "#{user.username}"
end
```
I get this output
```
D, [2018-08-08 12:30:42 +08:00 #60265] DEBUG -- : [848µs] SELECT * FROM user
Unhandled exception: You cannot access to the field `username` because it never has been initialized (Exception)
  from lib/clear/src/clear/model/column.cr:0:5 in 'value'
  from src/lib/models.cr:4:3 in 'username'
  from src/main.cr:8:8 in '->'
  from lib/clear/src/clear/model/collection.cr:255:3 in 'each'
  from src/main.cr:7:1 in '__crystal_main'
  from /usr/local/Cellar/crystal/0.25.1/src/crystal/main.cr:104:5 in 'main_user_code'
  from /usr/local/Cellar/crystal/0.25.1/src/crystal/main.cr:93:7 in 'main'
  from /usr/local/Cellar/crystal/0.25.1/src/crystal/main.cr:133:3 in 'main'
```

As best I can tell, I'm following the manual correctly here. Is there something I'm missing here?

**Comment by anykeyh** [comment]
Hello,

Clear tells your that your recordset didn't output username. 

While the models are created, the field `username` remains empty, thus disallowing you to get the value.

I bet this query will fail:
```crystal
User.query.select("username").each do |user|
  puts "#{user.username}"
end
```

Can you show me the schema of the columns of your database?

**Comment by shayneoneill** [comment]
I ended up using granite instead, and it worked. I don't know why it wouldn't work. There was clearly records there, and the field was called username.

**Comment by anykeyh** [comment]
Ok it's very weird,

I've tried your schema, but I cannot reproduce the bug. If one day you have time to investigate further, it would be great 👍

**Comment by anykeyh** [comment]
Update: I found out the issue. `user` is a reserved keyword in Postgres and must be escaped using double-quote. Clear do not yet escape the table name / variable name, so basically any reserved fields like `order` or `user` will throw an error. I'm going to fix it in the next days

**Comment by shayneoneill** [comment]
Ahah, yes that would do it. Probalbly best to throw backticks around the table and field names
