### ISSUE TITLE
Unable to resave record that failed to save

### ISSUE THREAD

**Issue by Blacksmoke16** [anykeyh/clear#39]
Since `@persisted` is set _before_ the actual SQL query is ran to insert a record, if the insert raises an exception, FK constraint validation for example, the record would not be inserted.  But, since the record is marked as `persisted` calling `record.save` again does nothing.

Probably could do something like:

`has_saving.cr`
```Crystal
            begin
              hash = Clear::SQL.insert_into(self.class.table, to_h).returning("*").execute(@@connection)
            rescue ex
              raise ex
            else
              @persisted = true
              self.set(hash)
            end
```
Which would only mark the record as persisted if it was saved without exceptions, otherwise pass the exception up.

A way to reproduce this would be like:
```Crystal
loc = Model.create({xxx}) # Model that has a FK in DB to another table, try to create a new record with invalid FK

begin
  loc.save # Try and save the record with the invalid FK
rescue ex : PQ::PQError
  OtherModel.create({xxxx}) # Create a record in the other table to satisfy the FK constraint in first table
ensure
  loc.save # Save the first model again
end

**Comment by anykeyh** [comment]
Great ! 

If you have time, can you send a PR since you already fixed it 😄

(And there's a perk, to be in the contributor list 😎)

**Comment by anykeyh** [comment]
You should catch the raise into the `temporary` block. It won't rollback in this case:

```crystal
expect_raises{ model.save! } #< Won't trigger the rollback. If it does, it's another bug ! :o
model.persisted?.should eq(false) #< This is wrong in the current implementation
```

**Comment by Blacksmoke16** [comment]
@anykeyh Thats what im doing, see #40

**Comment by anykeyh** [comment]
I understand now, my bad 😃. 

I'll check later this day how to pass-through this !
