### ISSUE TITLE
Unable to install clear with shards

### ISSUE THREAD

**Issue by Vici37** [anykeyh/clear#47]
Hello! Unfortunately I'm running into an issue with installing clear in new projects or updating it in old projects.

Running clear with `shards install` or `shards update` fails with:

```Failed git ls-tree -r --full-tree --name-only v0.3.1 -- shard.yml (). Maybe a commit, branch or file doesn't exist?```

This began happening after updating crystal to 0.27.0 .

## Reproduction Steps
1. `crystal init app new-cr-app`
2. Add:
```
dependencies:
    clear:
        github: anykeyh/clear
```
to `new-cr-app/shards.yml`
3. run `shards install` within the new crystal project

The full output that I see is:
```
Fetching https://github.com/anykeyh/clear.git
Failed git ls-tree -r --full-tree --name-only v0.3.1 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

This may be a bug with shards, but I see other projects being installed without issue in another project of mine, so trying here first.

## Other Details
```
> shards --version                                                                                                                                                                               
Shards 0.8.1 [0147a56] (2018-11-01)
> crystal --version                                                                                                                                                                           
Crystal 0.27.0 [c9d1eef8f] (2018-11-01)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

Let me know if there're any other details I can provide.

**Comment by Vici37** [comment]
A quick update, modifying and building shards locally and using it to install produces the new message:

```
...
Failed git ls-tree -r --full-tree --name-only v0.3.1 -- shard.yml (fatal: Not a valid object name v0.3.1
). Maybe a commit, branch or file doesn't exist?
```

**Comment by anykeyh** [comment]
Hello, I've made a typo mistake in the release! now it should works.

As of now, the lib is still in alpha and I would recommend you to add `branch: master` in the dependencies as the versions releases are not 100% stable.

Regards,

**Comment by Vici37** [comment]
Awesome, thank you!
