### ISSUE TITLE
[Question] Deleting a record

### ISSUE THREAD

**Issue by Prutya** [anykeyh/clear#5]
Hi,
Looks like there is only one way to delete a record:
```crystal
def destroy(env)
  id = env.params.url["id"].to_i
  group = TodoGroup.find!(id)
  delete_query = Clear::SQL::DeleteQuery.new.from("todo_groups").where({ id: id }).to_sql
  Clear::SQL.execute(delete_query)
end
```
Am I right?

**Comment by anykeyh** [comment]
Hello,

Indeed, it did looks like I forgot to implement model deletion 😅 .

I'm going to fix this today, you will be able to call `destroy` on the model tomorrow.

**Comment by anykeyh** [comment]
It's now done.

Note than the method is `delete` like in SQL and not `destroy` like in ActiveRecord.

**Comment by Prutya** [comment]
Great, thank you ☺️
