### ISSUE TITLE
Calling count from secondary DB throws exception

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#66]
If you init Clear with more than 1 database, and call `count` on any table from the secondary DB, it seems that clear tries to use the `default` DB to run the count throwing an error:

> Unhandled exception: relation "that_secondary_db_table" does not exist (PQ::PQError)

To test this, setup 2 databases then connect to them:

```crystal
Clear::SQL.init({
  "default" => "default_connection",
  "secondary"   => "secondary_connection"
})

DefaultModels::User.query.count #=> 0_i64
SecondaryModels::Post.query.count
# Unhandled exception: relation "posts" does not exist (PQ::PQError)
```

This may even be for all the aggregate methods, but I haven't checked in to it. Querying the secondary does work fine though aside from this.

**Comment by jwoertink** [comment]
Ok, just a little more information in to this...

The aggregate methods eventually call [scalar](https://github.com/anykeyh/clear/blob/master/src/clear/sql/query/fetch.cr#L59) where this point the `connection_name` is always "default". Passing in `self.connection_name` from [here](https://github.com/anykeyh/clear/blob/master/src/clear/sql/query/aggregate.cr#L24) (as well as the other places) would technically patch this, but that doesn't seem the cleanest way.

**Comment by anykeyh** [comment]
Good pick; I missed to add a link between `Model.connection` and `Collection(T)#connection_name`.

This has been fixed just now 🍾 !
