### ISSUE TITLE
Virtual Fields

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#68]
Hello! I've got a question/query on functionality that I'm not sure exists.

I have the following model:
```crystal
class User::Model
  include ApplicationModel
  include Authable::ByPassword

  self.table = "users"

  with_serial_pkey type: :uuid
  column email : String
  column encrypted_password : String?

  before(:create) do |model|
    model = model.as(self)

    password = model.password
    if password.is_a?(String)
      model.encrypted_password = Authable.generate_encrypted_password(password)
    end
  end
end
```

Where I'd create a model instance as so:

```crystal
User::Model.create!({email: "test", password: "hello"})
```

And I would like to encrypt a password on the before_create hook (a little Rails-y I know) but I'm having issues instantiating non-persisted fields into the model (often known in other ORM's as virtual fields).

Is this something that's currently supported? Or is there another way of handling this?

If its not the case, or not recommended to do it this way, I can always handle the encrypted assignment in an abstraction layer somewhere above the models.

**Comment by anykeyh** [comment]
Hello,

Indeed, that's a good point. Currently the constructor of the model discard the tuple or hash key which are not mapped as a column, making construction with addition of virtual field impossible through constructor.

I'll figure out if there's a way to make it works. I remember a shard which was creating "auto-constructor" by defining initializers using all the fields of the object. I'll see if it's possible to inspire Clear's code using this.

**Comment by anykeyh** [comment]
I've made a fix just now !

You can now pass non-persistent property key to NamedTuple in create/build/set methods; this will call the setter.

For your password management, I recommend you using already incuded (but not yet documented) Bcrypt support:

```crystal
class User::Model
      #...
      column encrypted_password : Crypto::Bcrypt::Password
      
      def password=(password)
        self.encrypted_password = Crypto::Bcrypt::Password.create(password)
      end

      def password
         self.encrypted_password
      end
end

mdl = User::Model.create!(password: "abcd")
mdl.password == "abcd" #< true !
```

**Comment by jackturnbull** [comment]
Thanks for the quick turnaround, that was a nice surprise! I'll take a look tonight :) I've also had a look at the Bcrypt extension and it seems useful, thanks for the pointer.
