### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by manveru** [anykeyh/clear#7]
I'm not sure what's going on there, but install fails because of the postinstall (which I don't even want to run)

```
Installing clear (0.1.0 at HEAD)
git ls-tree -r --full-tree --name-only HEAD -- shard.yml
git archive --format=tar --prefix= HEAD | tar -x -f - -C '/mnt/big/github/manveru/ainix/lib/clear'
git log -n 1 --pretty=%H HEAD
Postinstall ./bin/install-cli
rm -rf '/mnt/big/github/manveru/ainix/lib/clear'
Failed ./bin/install-cli:
/bin/sh: line 1: ./bin/install-cli: No such file or directory
```

**Comment by anykeyh** [comment]
Hello,

Currently the CLI command is not working (I'm planning to finalize it during the month).

However the ORM itself is working. Feel free to check the sample sources on how to use it.

**Comment by anykeyh** [comment]
Ah, nevermind, it starts by itself, just read again ! I'll disable the postinstall script.
