### ISSUE TITLE
KSUID Support

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#70]
No problem if this isn't something you deisre (which I would understand) but I'm slightly interested in KSUID's as primary keys. From what I can see of the codebase it seems like it would be possible at least.

Crystal implementation: https://github.com/Sija/ksuid.cr

In `with_serial_pkey` could generate a new KSUID with `ksuid = KSUID.new` and since its a 128 bit number like UUID, it will work with both UUID columns and String columns.

**Comment by anykeyh** [comment]
Philosophically, I want Clear to offer many different extension directly integrated to the gem. By default theses extensions won't be activated, but can be required at wanted `require("clear/ext/ksuid")`.

I'll figure out what is not extendable easily as of now (e.g. `with_serial_pkey`) and fix the code to make it easy to deal with.

Then we may work on a PR together to implement it in the shard (which wouldn't be a big deal, the concept is really simple)

**Comment by jackturnbull** [comment]
FWIW - I've settled on UUID's. KSUIDs would be nice but there's a lot of external data that I need to model within my app which relies on a UUID primary key, so I'm planning on using UUIDs throughout my app.

Since there's no point in focusing on things people don't actively need or use I'll close this one down but I'm happy to jump back in and assist if you or anyone else finds that they desire it.
