### ISSUE TITLE
What's happened with a README.md?

### ISSUE THREAD

**Issue by vifreefly** [anykeyh/clear#71]
Hello! When I first time found your project, it has very cool and self-describing README.md file. Just on the single page I had an idea about the project and how cool is it. Today I came back I found that readme is gone. Looks like you're working on some gitbook but it's not finished yet. 

Anyway, to have basic description about all the nice features right in the README.md will be nice, so people can check it without spending much time digging into docs, and pick **Clear** as an ORM for their projects.

**Comment by anykeyh** [comment]
Yep, I might have cleaned a bit too much the README. I'm trying currently to rationalize and improve the documentation, so any input to helps me improve is encouraged 😄 

I'll revert it back once I've cleaned it a bit.
