### ISSUE TITLE
Unable to fetch UUID foreign-keyed belongs_to association

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#74]
I just want to say off the bat that there's a reasonable chance that I could be doing something wrong here - but I've tried to look through some of the more obvious bits of code and I can't seem to get far. It appears to be because UUID doesn't exist in the union type of Clear::SQL::Any used within the CacheKey class. Adding it led to another error because UUID#to_json isn't a function.

Here's some minimal code to replicate:
```sql
CREATE TABLE users (
  id UUID PRIMARY KEY
);

CREATE TABLE agents (
  id UUID PRIMARY KEY,
  user_id UUID REFERENCES users (id)
);
```
```crystal
require "clear"

class User
  include Clear::Model

  with_serial_pkey type: :uuid
  has_one agent : Agent
end

class Agent
  include Clear::Model

  with_serial_pkey type: :uuid
  belongs_to user : User, foreign_key: "user_id", key_type: UUID
end

user = User.create()
agent = Agent.create({ user: user })
p agent.user
```

With the console error of:
```
instantiating 'Clear::Model::QueryCache#hit(String, UUID, User.class)'
in lib/clear/src/clear/model/query_cache.cr:47: no overload matches 'Clear::Model::QueryCache::CacheKey.new' with types String, UUID, String
Overloads are:
 - Clear::Model::QueryCache::CacheKey.new(relation_name : String, relation_value : Clear::SQL::Any, relation_model : String)

    @cache.fetch CacheKey.new(relation_name, relation_value, T.name) do
                          ^~~
```

**Comment by anykeyh** [comment]
The problem lay down in `key_type: UUID`; While there 's a UUID object in Crystal, it is not managed by Clear yet in relations.

Set `key_type: String` as of now, as UUID are like String in the SQL query building system.

**Comment by jackturnbull** [comment]
Thanks for the rsponse and that was my initial feeling as I know the pg driver doesn't have native UUID support, but moving it over to a string yeilded another issue, with the above example code:
```
no overload matches 'Clear::Model::Column(String)#value=' with type UUID
Overloads are:
 - Clear::Model::Column(T)#value=(x : UnknownClass)
 - Clear::Model::Column(T)#value=(x : T)
```

**Comment by anykeyh** [comment]
Indeed, I'll push a fix later today ! :+1:

**Comment by jackturnbull** [comment]
No rush - thanks for the help. I was able to make this work by avoiding with_serial_pkey and instead setting the primary key type to `String`, although keeping the with_serial_pkey helper would be preferable! :)

**Comment by anykeyh** [comment]
I'm glad you were able to do it. 

I'm working on the fix but it seems to be harder than expected; the problem lay down into the Converter system and fixing it will take more change than expected.

**Comment by anykeyh** [comment]
I made the change; it should fix your problem :smile:

**Comment by jackturnbull** [comment]
Oh nice! I really can't knock your productivity dude, it's impressive

It's could be a minor thing to some people but the speed you manage to respond to these sorts of issues keeps me comfortable working with this library. Building applications around relatively-unused libraries can be a little scary but since you manage to sort things so quickly it keeps those fears at bay. Just thought it was worth calling out! 😃

**Comment by anykeyh** [comment]
Thank you, it's heart-warming 😄. It's true hundred of hours have been spent the last two year on this project. To be honest as of now I just toyed around with Clear while building it, but I'm in the pre-production of a big project for a client. We already agreed to use Crystal and Clear for the backend. This will be the moment of truth and probably the v1.0 will born after that 😉

**Comment by anykeyh** [comment]
So basically, I'll help you as much as I can over your project; feel free to spam the issue box 👍

**Comment by Timbus** [comment]
Hello. Sorry to dig up this thread but I seem to be having the same problem when accessing related records through the `has_many` mapping. Was that supposed to be fixed by your merge? It looks like only the `belongs_to` was altered.

**Comment by anykeyh** [comment]
Thank you for pointing it out. I saw you're creating a pull request; feel free to ask if you need any helps.

**Comment by jackturnbull** [comment]
To add to this, I also appear to be still seeing this issue when querying `with_XXX` methods. Specifically in this case a belongs_to.

```
[watch:cr] instantiating 'Clear::Model::QueryCache#set(String, UUID, Array(Models::Web::Client::Entity))'
[watch:cr] in lib/clear/src/clear/model/query_cache.cr:60: no overload matches 'Clear::Model::QueryCache::CacheKey.new' with types String, UUID, String
[watch:cr] Overloads are:
[watch:cr]  - Clear::Model::QueryCache::CacheKey.new(relation_name : String, relation_value : Clear::SQL::Any, relation_model : String)
[watch:cr]
[watch:cr]     @cache[CacheKey.new(relation_name, relation_value, T.name)] = arr.unsafe_as(Pointer(Void))
```

**Comment by anykeyh** [comment]
Ok that's a bug I used to fix already for has_many cache system. I'll fix it in the next release
