### ISSUE TITLE
How do I update with JSON::Any column?

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#77]
If I have a model with a `JSON::Any` column, how do I update that?

```crystal
class Post
  include Clear::Model
  column id : Int64, primary: true
  column tags : JSON::Any
end

p = Post.find(1)
p.tags["test"] = 1
#=>  undefined method '[]=' for JSON::Any
```

This is assuming the `tags` column is defined like `tags jsonb DEFAULT '{}'::jsonb NOT NULL`

**Comment by jwoertink** [comment]
Ok, it looks like this works, but I'm wondering if there's an easier way...

```crystal
p = Post.find(1)
tags = p.tags.as_h
tags["test"] = JSON::Any.new(1_i64)
p.tags = JSON::Any.new(tags)
p.save
```

**Comment by anykeyh** [comment]
The current problem is than Crystal do not offers by default mutable JSON structure.

The best way would be to create a mutable structure and add converter, and not use JSON::Any anymore.

**Comment by jwoertink** [comment]
That makes sense. Maybe that could be added in? Like having a `alias HStore = Hash(String, String)` or something like that?

**Comment by anykeyh** [comment]
The HStore object is not yet mapped in Clear. 

One reason of why it's not possible to do that yet is `JSONB` fields can have root different than an object (pure value or array).

I'll figure out a solution, maybe getting inspired by the `env.body.json` object in Kemal

**Comment by anykeyh** [comment]
Following up, I'm preparing a shard to handle mutable JSONB, probably released in few hours/days It will be agnostic to Clear but with extension integrated. It will offers:

- mutation of a json object
- automatic detection for dirty state (no need to call manually dirty on the column).
- other cool features (I keep some good surprises, eh)

**Comment by jwoertink** [comment]
Sweet! Can't wait to check it out.
