### ISSUE TITLE
Avoid direct STDERR.puts log in SQL::Logger

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#78]
Line in question: https://github.com/anykeyh/clear/blob/master/src/clear/sql/logger.cr#L62

I've got some light tests around the behaviour of one of my transaction blocks and I want to allow an error to be thrown within the transaction so that I can ensure that another side-effect doesn't take place - e.g. file is not uploaded to S3 when user create fails, or transaction is rolled back when file upload fails.

I'm trying to generate a SQL-level fail in my transaction, which I'm able to do by referencing an associated ID that does not exist (PG causes a failure) but the direct STDERR output causes my test output to look a little rough:

<img width="696" alt="screenshot 2019-02-20 at 00 43 21" src="https://user-images.githubusercontent.com/3958636/53057754-8ad6e500-34a8-11e9-97bd-8d0248c750b2.png">

(for the record this is the type of change I'm happy submitting PR's for, but I just want to get a little more familar with the project before I start submitting those)

**Comment by anykeyh** [comment]
This problem is fixed in the next shipping (0.6): https://github.com/anykeyh/clear/blob/ff53e9adebf835782f0aed9ecf0d9a735b7a136f/src/clear/sql/logger.cr

By the way the fix might be worst than the previous problem. I'm assuming it crash in PG shards and encapsulate the real error into a Clear::SQL::Error block. 

Let see if this fix is good for you. Please keep the issue open as long as the branch is not merged in master 😄

**Comment by jackturnbull** [comment]
No problem, happy keeping it open! Thanks for the (very) rapid fix as well! Impressive 😃 

Personally, I much prefer the fact it's exposing a Clear::SQL::Error rather than nothing at all - it allows me to be more consistent with my error handling as I start to assume that I only need to know about the errors within Clear, and not any libraries beneath. Kind of like (I believe) ActiveRecord only exposes their own error classes and consider it part of their API, the further you move in this direction the less I'll then have to worry about whether I should he handling `Clear::SQL::Error | PQ::PQError` and let it become a case of `Clear::SQL::Error` only.

There's another advantage of encapsulating all errors in that you can begin to document the error types exposed by Clear and build a heirarcy of errors, which is difficult when it could be any error type raised from PQ.

Thanks again for the work!

**Comment by anykeyh** [comment]
This is fixed in 0.6 :smile:
