### ISSUE TITLE
Convert Model or Collection to JSON

### ISSUE THREAD

**Issue by aarongodin** [anykeyh/clear#80]
Hello, first off, great work so far on this library! I'm really enjoying it. I'm trying to convert models or collections of models to JSON and am encountering errors.

Here is the model I'm working with:

```crystal
require "json"
require "clear/core"

module Lizzy::Groups
  class GroupModel
    include Clear::Model

    self.table = "groups"

    column group_id : String, primary: true, presence: false
    column name : String
  end
end
```

I receive this error when using the `#to_json` that comes from including `Clear::Model`:

```
in /usr/share/crystal/src/json/to_json.cr:66: no overload matches 'Char#to_json' with type JSON::Builder
Overloads are:
 - Object#to_json(io : IO)
 - Object#to_json()

      each &.to_json(json)
```

I believe the error is because the column values returned from calling `to_h` are a union type of any value that could be in a column. Inspecting the stack trace, I see that the intermediate value from `#to_h` is this type:

```
Array(PG::BoolArray) | Array(PG::CharArray) | Array(PG::Float32Array) | Array(PG::Float64Array) | Array(PG::Int16Array) | Array(PG::Int32Array) | Array(PG::Int64Array) | Array(PG::StringArray) | Bool | Char | Clear::Expression::UnsafeSql | Float32
| Float64 | Int16 | Int32 | Int64 | Int8 | JSON::Any | PG::Geo::Box | PG::Geo::Circle | PG::Geo::Line | PG::Geo::LineSegment | PG::Geo::Path | PG::Geo::Point | PG::Geo::Polygon | PG::Numeric | Slice(UInt8) | String | Time | UInt16 | UInt32 | UInt64 | UInt8 | Nil
```

I'm relatively new to crystal--been using it on and off for about a year now. I understand there might need to be a step here to convert that union type into something that can be handled by the json conversion?

**Comment by anykeyh** [comment]
Hello,

Actually it's a problem occuring as you require only the core. There's Std lib extension to transform a char into json (file `src/clear/extensions/core_ext.cr`):

```crystal
struct Char
  def to_json(json)
    json.string("#{self}")
  end
end
```

I guess to use `to_json` feature you should include the whole library `require "clear"` instead of only the core version.

**Comment by aarongodin** [comment]
Oh awesome. Thanks for the clarification, it's working for me. :)
