### ISSUE TITLE
Using Crystal reserved words as association name

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#83]
I can seee this being a tricky one, so I'll understand if it's just something I need to work around, but I'm having an issue using the word 'module' in one of my belongs_to relationships. e.g.:

```crystal
module Models::Web::ModuleFeedback
  class Entity
    include Clear::Model

    with_serial_pkey type: :uuid
    belongs_to module : Models::Web::Module::Entity, foreign_key: "module_id", key_type: UUID
  end
end
```

Because 'module' itself is a reserved word in Crystal. I can get around this easily enough using 'web_module' (or similar) as the name of the relation.

Is there a simple enough way around this or is this a hard issue due to Crystal itself?

**Comment by anykeyh** [comment]
Yep you need to rename the relation. You cannot use some keywords as relation name.

**Comment by jackturnbull** [comment]
That's fine - I was expecting this to be a `wontfix` from the get-go but was checking to see if there was something I was missing (e.g. passing the relation name as a string).

I'll close this one down
