### ISSUE TITLE
Logger coloring option

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#84]
The coloring output for the logs in development are great because it allows you to read and understand the queries really easy. However, in production when shipping logs off to a 3rd party (timber.io) or outputting the errors in something like bugsnag, all of the escape characters make it so much more difficult to read.

This is a small snippet it to show, but the SQL is really large. It would be nice to have a way to customize this

![screen shot 2019-03-05 at 11 30 58 am](https://user-images.githubusercontent.com/2391/53831653-2bfa7c80-3f3a-11e9-842b-122743140ab8.png)

```crystal
Clear.logger_coloring = ENV["APP_ENVIRONMENT"]? == "development"
# something like that, or maybe....
Clear.logger.enable_color = true
```

**Comment by anykeyh** [comment]
The logger use `colorize` from stdlib.

You might want to add `Colorize.enabled = false` and it should work.  There's even `Colorize.on_tty_only!` which detect the target of the output and might be useful in your context 😄 .

Tell me if it fix your problem !

**Comment by jwoertink** [comment]
That's awesome! I didn't know that existed. Thanks, I'll close this out.
