### ISSUE TITLE
How to truncate a table?

### ISSUE THREAD

**Issue by grantspeelman** [anykeyh/clear#88]
Hi 

I am not sure how I would truncate or delete all rows in a table?

```crystal
class Account
  include Clear::Model

  column id : Int32, primary: true, presence: false
  column email : String
  column hashed_password : String
end
```

I have tried things like:
* Account.clear
* Account.delete_all
* Account.truncate

All without any luck. 
Also can't seem to find anything on how to do this in the documenation.
Could you please help?
Thank you

**Comment by anykeyh** [comment]
Hello,

Indeed, the batch deletion is in the wrong chapter in the documentation:
https://clear.gitbook.io/project/model/batchs-operations/bulk-update

The way to do it is to transform the select query (the collection object) to a delete query like this:

```crystal
Account.query.to_delete.execute
```

**Comment by grantspeelman** [comment]
Thank you for you help.

Do you think it would be a worthwhile feature to add something like this?

```crystal
Account.query.truncate.execute
# and
Account.query.truncate(cascade: true).execute
```

**Comment by anykeyh** [comment]
I will add this feature in the next version of clear, but probably define it in lower level `Clear::SQL` module like this:

```crystal
Clear::SQL.truncate(tablename: ModelClass | String , [cascade: true], [identity: "restart|continue"])
```

**Comment by grantspeelman** [comment]
thank you, that would be awesome
