### ISSUE TITLE
Fetching associations from created model

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#92]
Hopefully a really simple one but not been able to find it within the docs. I'm creating models using factories, where the associations aren't exposed outside of the return methods - only the returned instance of user is available. I want to try and access properties on the associated models from the returned user:

```crystal
class Organization
  include Clear::Model
  primary_key type: :uuid
end

class User
  include Clear::Model
  primary_key type: :uuid
  belongs_to organization : Organization, key_type: UUID
end
```

How go I get values for the organization from the returned user?

```crystal
organization = Organization.create
user = User.create({organization: organization})
p user.organization.id
```
```
in src/lib/models/web/__tests__/resource_test.cr:12: undefined method 'id' for Nil (compile-time type is (Models::Web::Organization::Entity | Nil))

        p organization.id
```
There are some references to `fetch_fields` and `with_organization` but this doesn't seem to apply here.

Outside of testing, my other use case is to create entities from a repository layer, return only the entity itself, but then normalize some fields from that returned entity.

**Comment by jackturnbull** [comment]
🤦‍♂️

I've been in javascript-land a little too long this week and forgot that I only needed to assert (or guard against) not nil.

`p user.organization.not_nil!.id`

Closing this one out.

**Comment by anykeyh** [comment]
Hello !

Currently the `belongs_to` structures are always Nilable; this is a limitation which helped me to write the code faster, but in future version you will be able to choose if you want the object to be nilable or not, like other columns.

Meanwhile you can also use `user.organization!` which do the `not_nil!` for you but is faster to write.

**Comment by jackturnbull** [comment]
Ah that would make a lot of sense, I'd assumed that it was because the column wasn't set as 'fetched' but non-nilable would be a nice benefit. WIll use your shorthand for the time being - thanks for the tip :)
