### ISSUE TITLE
Raising Clear::SQL::RecordNotFoundError error instead of NilAssertionError on find!(id)

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#94]
More of a discussion, as there are multiple ways to handle this but I quite like the way ActiveRecord rasies a RecordNotFound error message when performing find operations.

It's somewhat minor (and up for debate if this is the correct approach) but throwing a Clear::SQL namespaced error would allow me to add a generic handler for `Clear::SQL::RecordNotFoundError` in my parent API controllers and mean that I could skip guarding each of my update find methods with a method that checks for the presence of the model.

The main motivation for a more specific class is that catching NilAssertionError is too generic of an error to reliably assert behaviour upon.

https://github.com/anykeyh/clear/blob/bba7c6fc13ab35f453d32e99f7de944ab33141fe/src/clear/model/modules/class_methods.cr#L108-L110

Could become something like:

```crystal
def find!
  result = find(x)
  raise Clear::SQL::RecordNotFoundError.new unless result
  result
end
```

If this is something you agree with and want to hand over to me, feel free to let me know and I'll raise a PR 😄 

Ref: [[1]](https://api.rubyonrails.org/classes/ActiveRecord/RecordNotFound.html)

**Comment by anykeyh** [comment]
I think all the errors should be mapped to a specific type as much as possible. 
So I'm more than ok for the PR ! :smile:
