### ISSUE TITLE
Serializing classes to jsonb columns?

### ISSUE THREAD

**Issue by Timbus** [anykeyh/clear#95]
Hi there. I was wondering if there was a good way to serialize a structured data format to a JSONB column. In my case, an Address:

```cr
  struct Address
    include JSON::Serializable
    getter street_address : String
    getter city : String
    getter state : String
    getter postcode : String

    def initialize(@street_address, @city, @state, @postcode)
    end
  end
```
Needs to be converted from a `JSON::Any`:
```cr
  class Address::Converter
    def self.to_column(address) : Address?
      if address.is_a? JSON::Any
        Address.new(
          address["street_address"].as_s,
          address["city"].as_s,
          address["state"].as_s,
          address["postcode"].as_s,
        )
      else
        nil
      end
    end

    def self.to_db(address : Address?)
      address.try &.to_json
    end
  end
```
From what I can see, Clear will convert a JSONB column to a JSON::Any automagically but this is a problem..
I was wondering if there was a way to just pull the JSONB as a string so that I didn't have to unpack it from a JSON::Any? Or even better, support JSONable types in general?

**Comment by Timbus** [comment]
Actually, it looks like PG is responsible for the conversion: https://github.com/will/crystal-pg/blob/cafe761ead8f5189fab9de97dec9d05652a305df/src/pg/decoder.cr#L320

Overriding this would work but it seems like a bad idea.

**Comment by anykeyh** [comment]
Hello,

Yes, currently this is an auto-conversion done by `pg` shard so I won't fix. You can call `to_json` of `JSON::Any` in the converter but it will make some overhead.

I'm closing it for now; would be glad to fix it if there's some changes in shard `pg` first :wink:
